name: adaptive-attack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py310h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.5.0=py310hff52083_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py310h06a4308_0
  - conda-package-streaming=0.10.0=py310h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.9.0=py310h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py310h06a4308_0
  - fmt=9.1.0=hdb19cb5_1
  - freetype=2.12.1=h4a9f257_0
  - frozendict=2.4.2=py310h5eee18b_0
  - fsspec=2024.3.1=py310h06a4308_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=7.0.1=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=py310h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libarchive=3.6.2=h6ac8c49_3
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py310h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.4=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - menuinst=2.1.1=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_1
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py310h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py310h5eee18b_0
  - platformdirs=3.10.0=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - prompt-toolkit=3.0.47=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py310h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py310h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.2=py310h06a4308_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - safetensors=0.4.2=py310ha89cbab_1
  - setuptools=69.5.1=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py310_cu121
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.66.4=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - truststore=0.8.0=py310h06a4308_0
  - typing-extensions=4.11.0=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py310h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - accelerate==0.32.1
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alpaca-eval==0.6.3
      - altair==5.3.0
      - annotated-types==0.7.0
      - anthropic==0.30.1
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.20.0
      - deepspeed==0.14.4
      - dill==0.3.8
      - diskcache==5.6.3
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - email-validator==2.2.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - fire==0.6.0
      - flashinfer==0.1.2+cu121torch2.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fschat==0.2.36
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==3.40.0
      - gradio-client==1.1.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.25.2
      - huggingface-hub==0.23.4
      - importlib-resources==6.4.0
      - interegular==0.3.3
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lark==1.1.9
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lm-eval==0.4.3
      - lm-format-enforcer==0.10.1
      - lxml==5.2.2
      - markdown-it-py==2.2.0
      - markdown2==2.4.13
      - matplotlib==3.9.1
      - mbstrdecoder==1.1.3
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nh3==0.2.17
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numba==0.60.0
      - numexpr==2.10.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.36.0
      - openpyxl==3.1.5
      - orjson==3.10.6
      - outlines==0.0.46
      - pandas==2.2.2
      - pathvalidate==3.2.0
      - patsy==0.5.6
      - peft==0.12.0
      - pip==24.1.2
      - plotly==5.22.0
      - portalocker==2.10.0
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.1
      - pycountry==24.6.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydantic-settings==2.3.4
      - pydub==0.25.1
      - pyparsing==3.1.2
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - ray==2.32.0
      - referencing==0.35.1
      - rich==13.7.1
      - rouge-score==0.1.2
      - rpds-py==0.19.0
      - ruff==0.5.1
      - sacrebleu==2.4.2
      - schedulefree==1.2.7
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - starlette==0.37.2
      - svgwrite==1.4.3
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - tenacity==8.5.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.8
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm-multiprocess==0.0.11
      - transformers==4.42.3
      - triton==2.3.0
      - trl==0.9.4
      - typepy==1.3.2
      - typer==0.12.3
      - tyro==0.8.5
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - ujson==5.10.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vllm==0.5.1
      - vllm-flash-attn==2.5.9
      - wandb==0.17.7
      - watchfiles==0.22.0
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
      - word2number==1.1
      - xformers==0.0.26.post1
      - xxhash==3.4.1
      - yarl==1.9.4
